apiVersion: v1
kind: Secret
metadata:
  name: notevault-api-secret
  namespace: notevault-prod
type: Opaque
data:
  # Ganti dengan base64 encoded Production Key kamu
  SUPABASE_KEY: "c2JfcHVibGlzaGFibGVfYVdON1U3a0JLZUFOSGJWUC12dWRiQV9YOEwtbXFycg==" # placeholder
