apiVersion: v1
kind: Service
metadata:
  name: notevault-api-service
  namespace: notevault-prod
spec:
  selector:
    app: notevault-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  # Di production, biasanya menggunakan ClusterIP karena diakses via Ingress Controller
  type: ClusterIP
